### ISSUE TITLE
Exception: Could not read file.

### ISSUE THREAD

**Issue by dwbatten** [EricWilbanks/faseAlign#22]
Hey there,

I've been learning to use faseAlign and had good luck so far. I've run into issues today with a couple of files though, and I'm not sure how to interpret the error I'm getting.

It worked yesterday (and continues to work) with other .wavs and .TextGrids that I have segmented and transcribed in Elan using an identical process. I'd appreciate any help in interpreting this to know why the file would be unreadable and how I could resolve the issue. Thanks!

(base) MacBook-Pro-78:~ dbatten$ fasealign -w /Users/.../id_2.wav -t /Users/.../id_2.TextGrid -o /Users/.../Documents -p
Traceback (most recent call last):
  File "/Users/dbatten/opt/miniconda3/bin/fasealign", line 884, in <module>
    main(args.wav, args.stereo, args.left, args.right, args.transcript, args.outpath, args.name, args.missing, args.syllables, args.phonemicize, args.tags, args.version, args.tier)
  File "/Users/dbatten/opt/miniconda3/bin/fasealign", line 831, in main
    missing, chunk_index, total_chunks= make_mlf_from_tg(dict_all,audio_align,tmppath,basename,args_transcript,channel_type,chan_1,chan_2,args_phonemicize,dict_path,args_tier)
  File "/Users/dbatten/opt/miniconda3/bin/fasealign", line 467, in make_mlf_from_tg
    lm = audiolabel.LabelManager(from_file = textgrid, from_type = 'praat', codec ='utf-8')
  File "/Users/dbatten/opt/miniconda3/lib/python3.7/site-packages/audiolabel.py", line 722, in __init__
    self.read_praat(from_file)
  File "/Users/dbatten/opt/miniconda3/lib/python3.7/site-packages/audiolabel.py", line 1018, in read_praat
    self.read_praat_long(filename)
  File "/Users/dbatten/opt/miniconda3/lib/python3.7/site-packages/audiolabel.py", line 1202, in read_praat_long
    if line == '': raise Exception("Could not read file.")
Exception: Could not read file.

**Comment by EricWilbanks** [comment]
Sorry for the delay on responding to this.  And thanks for including the error messages as well; they're helpful in potentially diagnosing the issue. 

The error is arising when the audiolabel package we use to read in the textgrids is processing the header of the textgrid file. From the line that causes the error, it appears that it's encountering an empty line where it's not expecting one. This is potentially related to differences in how ELAN and Praat export textgrids, since I believe the audiolabel package was written following the assumptions of textgrids generated in Praat. 

Would you be able to share a minimal example of a textgrid that causes this error? The audio isn't necessary to test this bug, and we don't really need any content in the textgrid except whatever is causing the error (probably an unexpected empty line).

If that's not a possibility, I'll attempt to create a problematic textgrid out of ELAN and see if I can diagnose the issue, and then pass it on to the audiolabel creator.

Thanks!
Eric

**Comment by dwbatten** [comment]
Eric,

Thanks for getting back to me!

So I've figured it out. In doing so, I fixed it in Elan as well and in the Textgrid that was causing issues, so I don't have those troublemaking files on hand.

As you suspected, however, it was a blank bit in a textgrid. Namely, it was a couple of _very _quietly_ filled pauses in some L2 speech that I missed in segmenting and transcribing. I assume it was perceiving that as speech and failing when it hit those lines. 

I went back, segment and transcribed as {NS}, and it worked beautifully.

**Comment by EricWilbanks** [comment]
Glad to hear that locating the empty interval solved the issue! I'll flag this unintended behavior in the ELAN > TextGrid conversion process to the creator of audiolabel in case he wants to address it, otherwise we know the workaround now.
